/**
* @file     prob1.c
* @author   Stavros Vagionitis
* @date     13 Feb 2015
* @brief    [Problem 2 in Project Euler](https://projecteuler.net/problem=2)
*           Even Fibonacci numbers
*           ====================
*           Each new term in the Fibonacci sequence is generated by adding the
*           previous two terms. By starting with 1 and 2, the first 10 terms
*           will be:
*
*           1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
*
*           By considering the terms in the Fibonacci sequence whose values
*           do not exceed four million, find the sum of the even-valued terms.
*/

#include <stdlib.h>
#include <stdio.h>

/**
 * \brief Check if a number is multiple of another number.
 *
 * \param   num     The number to check if it's multiple
 * \param   mult    The multiple to be checked.
 * \return  1 if it's multiple, 0 if not.
 */
uint8_t isMultiple(uint64_t num, uint64_t mult)
{
    if (num % mult == 0)
        return 1;
    else
        return 0;
}

/**
 * \brief Calculate the terms of Fibonacci sequence.
 *
 * \param   term    The Fibonacci term to be calculated.
 *                  Starts from term 0. Term 0 is 1 and
 *                  term 1 is 2.
 * \return the Fibonacci term.
 */
uint64_t fibSequence(uint64_t term)
{
    uint64_t term0 = 1;
    uint64_t term1 = 2;

    if (term == 0)
        return term0;
    else if (term == 1)
        return term1;
    else if (term == 2)
        return term0 + term1;
    else
    {
        uint64_t termNm1 = term0 + term1;
        uint64_t termNm2 = term1;
        uint64_t termN = 0;
        for (uint64_t i = 3;i<=term;i++)
        {
            termN = termNm1 + termNm2;

            termNm2 = termNm1;
            termNm1 = termN;
        }

        return termN;
    }
}

/**
 * \brief Calculate the terms of Fibonacci sequence (Recursive way).
 *        It's slower than the non recursive way.
 *
 * \param   term    The Fibonacci term to be calculated.
 *                  Starts from term 0. Term 0 is 1 and
 *                  term 1 is 2.
 * \return the Fibonacci term.
 */
uint64_t fibSequenceRec(uint64_t term)
{
    if (term == 0)
        return 1;
    else if (term == 1)
        return 2;
    else
        return fibSequenceRec(term - 1) + fibSequenceRec(term - 2);
}

/**
 * \brief The solution using a naive way.
 *
 * \param   maxValue  The max value of Fibonacci term.
 * \return  1 if everything is ok, 0 if not.
 */
uint8_t solution1(uint64_t maxValue)
{

    uint64_t i = 0;
    uint64_t sum = 0;
    while(1)
    {
        // Calculte Fibonacci term
        uint64_t fib = fibSequence(i);

        if (fib > maxValue)
            break;

        // Get the sum of even-valued terms.
        if (isMultiple(fib, 2))
            sum += fib;

        i++;
    }

    fprintf(stdout, "Sum: %u\n", sum);

    return 1;
}

/**
 * \brief Usage of this program.
 *
 * \param   argv0   The first argument string which is the current executable.
 * \return  -1.
 */
int usage(char *argv0)
{
    fprintf(stdout, "%s <Max value of Fibonacci term.>\n", argv0);
    return -1;
}


int main(int argc, char *argv[])
{
    if (argc != 2)
        return usage(argv[0]);

    uint64_t maxValue = strtoull(argv[1], NULL, 10);

    solution1(maxValue);

    return 0;
}
