/**
* @file     prob45.c
* @author   Stavros Vagionitis
* @date     xx Mar 2015
* @brief    [Problem 45 in Project Euler](https://projecteuler.net/problem=45)
*           Triangular, pentagonal, and hexagonal
*           =====================================
*           Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:
*
*           Triangle 	  	Tn=n(n+1)/2 	  	1, 3, 6, 10, 15, ...
*           Pentagonal 	  	Pn=n(3n−1)/2 	  	1, 5, 12, 22, 35, ...
*           Hexagonal 	  	Hn=n(2n−1) 	  	1, 6, 15, 28, 45, ...
*
*           It can be verified that T285 = P165 = H143 = 40755.
*
*           Find the next triangle number that is also pentagonal and hexagonal.
*
*/

#include <stdlib.h>
#include <stdio.h>
#include <stdint.h>

/**
 * \brief Check if a number is multiple of another number.
 *
 * \param   num     The number to check if it's multiple
 * \param   mult    The multiple to be checked.
 * \return  1 if it's multiple, 0 if not.
 */
uint8_t isMultiple(uint64_t num, uint64_t mult)
{
    if (num % mult == 0)
        return 1;
    else
        return 0;
}

uint8_t isTriangle(uint64_t num)
{
    if (num == 1)
        return 1;
    else if (num == 3)
        return 1;
    else
    {
        uint64_t double_num = 2*num;

        for (uint64_t i = 3;i<=num;i++)
            if (double_num == (i*(i+1)))
                return 1;
    }

    return 0;
}

uint8_t isPentagonal(uint64_t num)
{
    if (num == 1)
        return 1;
    else if (num == 5)
        return 1;
    else
    {
        uint64_t double_num = 2*num;

        for (uint64_t i = 5;i<=num;i++)
            if (double_num == (i*(3*i-1)))
                return 1;
    }

    return 0;
}

uint8_t isHexagonal(uint64_t num)
{
    if (num == 1)
        return 1;
    else if (num == 6)
        return 1;
    else
    {
        for (uint64_t i = 6;i<=num;i++)
            if (num == (i*(2*i-1)))
                return 1;
    }

    return 0;
}

/**
 * \brief The solution using a naive way.
 *
 * \param   num  Number to do something.
 * \return  1 if everything is ok, 0 if not.
 */
uint8_t solution1(uint64_t num)
{

    for (uint64_t i = num;i>=1;i--)
    {
        if (isTriangle(i))
            if (isPentagonal(i))
                if (isHexagonal(i))
                    fprintf(stdout, "%ju is triangle and pentagonal and hexagonal!!!\n", i);
    }

    return 1;
}

/**
 * \brief Usage of this program.
 *
 * \param   argv0   The first argument string which is the current executable.
 * \return  -1.
 */
int usage(char *argv0)
{
    fprintf(stdout, "%s <Number to do something.>\n", argv0);
    return -1;
}


int main(int argc, char *argv[])
{
    if (argc != 2)
        return usage(argv[0]);

    uint64_t num = strtoull(argv[1], NULL, 10);

    solution1(num);

    return 0;
}
